site_name: TEURA
site_url: https://teura.eu/
site_description: Your R&D partner from concept to deployment.
site_author: Patryk Balazy
theme:
  name: mkdocs
nav:
  - Home: index.md
markdown_extensions:
  - attr_list
extra_css:
  - assets/extra.css
