site_name: TEURA
site_url: https://teura.eu/
site_description: TEURA â€“ software development, AI/ML engineering, PdM
site_author: Patryk Balazy
theme:
  name: mkdocs
nav:
  - Home: index.md
markdown_extensions:
  - attr_list
extra_css:
  - assets/extra.css
